/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SignpState } from "./interface";
export { SignpState } from "./interface";
export namespace Components {
    interface ContainerWrapper {
        "signUp": any;
    }
    interface FormComponent {
        "data": SignpState;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": any;
        /**
          * The last name
         */
        "last": any;
        /**
          * The middle name
         */
        "middle": any;
    }
    interface SecondTemplate {
        "data": any;
    }
}
declare global {
    interface HTMLContainerWrapperElement extends Components.ContainerWrapper, HTMLStencilElement {
    }
    var HTMLContainerWrapperElement: {
        prototype: HTMLContainerWrapperElement;
        new (): HTMLContainerWrapperElement;
    };
    interface HTMLFormComponentElement extends Components.FormComponent, HTMLStencilElement {
    }
    var HTMLFormComponentElement: {
        prototype: HTMLFormComponentElement;
        new (): HTMLFormComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSecondTemplateElement extends Components.SecondTemplate, HTMLStencilElement {
    }
    var HTMLSecondTemplateElement: {
        prototype: HTMLSecondTemplateElement;
        new (): HTMLSecondTemplateElement;
    };
    interface HTMLElementTagNameMap {
        "container-wrapper": HTMLContainerWrapperElement;
        "form-component": HTMLFormComponentElement;
        "my-component": HTMLMyComponentElement;
        "second-template": HTMLSecondTemplateElement;
    }
}
declare namespace LocalJSX {
    interface ContainerWrapper {
        "signUp"?: any;
    }
    interface FormComponent {
        "data"?: SignpState;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: any;
        /**
          * The last name
         */
        "last"?: any;
        /**
          * The middle name
         */
        "middle"?: any;
    }
    interface SecondTemplate {
        "data"?: any;
    }
    interface IntrinsicElements {
        "container-wrapper": ContainerWrapper;
        "form-component": FormComponent;
        "my-component": MyComponent;
        "second-template": SecondTemplate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "container-wrapper": LocalJSX.ContainerWrapper & JSXBase.HTMLAttributes<HTMLContainerWrapperElement>;
            "form-component": LocalJSX.FormComponent & JSXBase.HTMLAttributes<HTMLFormComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "second-template": LocalJSX.SecondTemplate & JSXBase.HTMLAttributes<HTMLSecondTemplateElement>;
        }
    }
}
